### PR TITLE
Set default Node.js version to 6.5.0

### PR DESCRIPTION
**Pull request by JonasHavers**

### CODE REVIEW

**Comment by BenWildeman** [comment]
I would wait until v6 enters LTS before bumping up the default. 3 weeks left

**Comment by GochoMugo** [comment]
@NitroGhost It is currently set to 6.4.0. So...

**Comment by BenWildeman** [comment]
That is true, but the node team have 3 weeks to finalise v6 for LTS. Once
it's in LTS, it will only be changing version when there's security
patches. Between now and when it's in LTS, it might change version a lot.
It makes more sense to wait so that the maintainer isn't bumping the
version regularly

**Comment by apihlaja** [comment]
@NitroGhost That's where the actual default version is defined: https://github.com/icflorescu/openshift-cartridge-nodejs/blob/master/lib/util#L9 (ie. it resolves to 6.5.0 already and PR is just for documentation).

The reasoning for "unstable" is here: https://github.com/icflorescu/openshift-cartridge-nodejs/issues/48#issuecomment-228767440 (ie. semver.io "stable" is heavily opinionated by Heroku staff, "unstable" is the lastest official release by node.js)

**Comment by BenWildeman** [comment]
@apihlaja when v6 lands in LTS, wouldn't the unstable start resolving to v7? still makes sense to wait 3 weeks to change the version because we know for sure that it's all changing on the 1st October

**Comment by apihlaja** [comment]
@NitroGhost semver.io resolves node "[stable](https://semver.io/node/stable)" to [5.11.1 at the moment](https://github.com/heroku/semver.io/issues/57), which is neither lastest or LTS. For me, it looks pretty random... They have [year old issue](https://github.com/heroku/semver.io/issues/49) about updating to new node.js versioning scheme but nothing has happened. I'd call whole site dead at this point.. I'd bet @icflorescu wouldn't mind to see PR removing semver.io ties but obviously, no one wants to spend much time for current gen Openshift when future is unknown.

**Comment by icflorescu** [comment]
Sorry for not pulling this earlier, but I'm currently in a long awaited trekking holiday with sporadic Internet connectivity :-)

**Comment by icflorescu** [comment]
Totally agree about semver's random definition of "stable" vs "unstable". That's why we have the option to force/lock the cartridge to a specific version.

**Pull request merged**
